### ISSUE TITLE
Enhancement:  Cauldron MacOS UI should remember python path 

### ISSUE THREAD

**Issue by cswarth** [sernst/cauldron#1]
Cauldron MacOS UI asks for python 3.5 path every time it start up.  
Looking forward to this being cached in a preferences config.

![screen shot 2016-09-23 at 9 50 04 am](https://cloud.githubusercontent.com/assets/295428/18794180/1edd451e-8173-11e6-9594-5d23331c94e6.png)

**Comment by sernst** [comment]
This was a regression. Thanks for pointing it out. It has been fixed in the latest UI release.
