### ISSUE TITLE
Cauldron exported notebooks file extension

### ISSUE THREAD

**Issue by smartin41** [sernst/cauldron#11]
I recently came across your Cauldron project, which looks to be a good alternative to Jupyter notebook.  However, I did notice that when sharing a notebook the filename extension is 'CDF'.  This is a very common filename extension in some scientific data circles (https://cdf.gsfc.nasa.gov).  So it becomes a bit of a nuisance if one wants to work with cauldron files and CDF scientific data files on the same platform.  Is there any chance the cauldron filename extension could be something else (how about .cau)?

**Comment by sernst** [comment]
@smartin41 Thanks for the info. I tried hard to find an extension that would minimize conflicts, but that one clearly doesn't. I'll look into alternatives.

**Comment by smartin41** [comment]
You may want to consider .CAU  
I did a quick google search on this extension and it looked to me to be unused.

**Comment by sernst** [comment]
Yeah, that's a good suggestion. I'll dig deeper to make sure, but initial searches look safe to me as well.
