### ISSUE TITLE
How to display a pandas Series?

### ISSUE THREAD

**Issue by lmr2391** [sernst/cauldron#12]
I guess you didn't implement this function yet. Sometimes I'm not aware whether an operation on a dataframe returns a dataframe or a table. When I try to display the result using the `cd.display.table` function, it yields the `AttributeError` 'Series' object has no attribute 'columns'

Since a Series is basicly a DataFrame with one column, it would make some sense to use the same function for displaying them. And when I just want to see the output of an operation I usually don't think it advance what type it is, so I would also like it to be the same function. However, having an own function feels more right because it forces you to be explicit.

Some example code:
```python
import cauldron as cd
import pandas as pd

series = pd.Series(range(1000))
print(type(series))

cd.display.table(pd.DataFrame(series)) # a possible hack would be to convert series' to dataframes first
print(series) # this works but isn't as nicely formatted
cd.display.table(series) # this fails
```

**Comment by sernst** [comment]
Good point. This should definitely be added.

**Comment by sernst** [comment]
Support for Pandas.Series has been added in release 0.1.4. It is now possible to use the `cd.display.table()` function to display a Series.
