### ISSUE TITLE
Raw strings instead of @ for display.latex

### ISSUE THREAD

**Issue by larsrinn** [sernst/cauldron#13]
Why do you recommend to use an `@` instead of an `\` for displaying latex equations? In my opinion this reduces readabiliy if you're already used to latex and adds an extra step when copy&pasting equations from another source/equation generator. What currently already works is using a raw string. At least I suggest to add this information to the documentation

```
cd.display.latex(r'\alpha @delta')
```

btw, I'm running Windows 10 and Python 3.5.3. I know of some issues between Linux and Windows when it comes to backslashes, but I guess this only true for everything touching the filesystem (?)

**Comment by sernst** [comment]
Yes, you make good points. The issues I encountered when trying to implement this weren't with the input in Python because you can use the raw string method as you've demonstrated. The problems occurred in the JavaScript. But I'll look into support for this because it would be nice.
