### ISSUE TITLE
Displaying dataframes with multiindexes

### ISSUE THREAD

**Issue by lmr2391** [sernst/cauldron#15]
Joining the values of multiple indexes with `', '` and calling the column `index` conceals some potentially important information and hinders the possibility to copy&paste from the output to excel (props for the fact, that this is posssible at all). Would it be possible/desirably for others, that each of the multiindex levels is written to an own column with their respective names? 

```python
import cauldron as cd
import pandas as pd
import numpy as np

rng = pd.date_range('1/1/2017', periods=8760, freq='H')
df = pd.DataFrame(
    {'value': np.random.rand(8760)},
    index=rng
)
df = df.groupby([df.index.month, df.index.day]).agg(['mean', 'std'])
df.index.set_names(['month', 'day'], inplace=True)
df.to_excel('foo.xlsx') # I like this formatting

print(df) # output unpleasant
cd.display.table(df, include_index=True) # Conceals too much information
```
### Output written to Excel
![grafik](https://user-images.githubusercontent.com/22575361/26991269-fcdc7cd8-4d59-11e7-921f-002a453fe8b2.png)

### Output from print
![grafik](https://user-images.githubusercontent.com/22575361/26991171-b28ec546-4d59-11e7-9a00-5dc96b981d2e.png)

### Output by `cd.display.table()`
![grafik](https://user-images.githubusercontent.com/22575361/26991289-15a98062-4d5a-11e7-8b8f-0db85f0b69bd.png)

Also it feels like I've been complaining quite a lot. This was absolutely not my intention. I really like the idea behind cauldron and think the work already put in is amazing. Just trying to make it even better ;)

**Comment by sernst** [comment]
@lmr2391 Thanks! I'm glad you're enjoying Cauldron. Not a problem. I always appreciate the suggestions for improvement. This is another good one that I'll dig into.
