### ISSUE TITLE
IPython magics missing

### ISSUE THREAD

**Issue by bofm** [sernst/cauldron#16]
Is there a way to make Jupyter/IPython magic commands work?

**Comment by sernst** [comment]
No there's no way to use IPython magic commands in Cauldron. Cauldron runs on standard Python, which does not have them and adheres to the "avoid magical side effects" programming paradigm. But if there are magic commands that you find useful and not easy to reproduce with standard Python, please let me know and I'll look into how Cauldron can implement them in a standard Pythonic way.
