### ISSUE TITLE
Importing local files throws error

### ISSUE THREAD

**Issue by thriveth** [sernst/cauldron#23]
When I try to import a file in the project folder (case in point, a file of data arranged in dicts, pandas Series and lists), it throws a ModuleNotFoundError. When doing the same in a normal python or IPython console or Jupyter kernel, it works fine. 

Am I doing anything wrong, or is this a bug?

Cauldron with Anaconda, Python 3.6 on Ubuntu 17.04.

**Comment by sernst** [comment]
Ah, yes. Thanks for pointing that out! It's been fixed in the latest release 0.1.4.
