### ISSUE TITLE
Enhancement:  collect version info in one place

### ISSUE THREAD

**Issue by cswarth** [sernst/cauldron#3]
It would be great, especially during early development, to have a button on the UI that collects relevant version information in one place that can be copy-pasted into a bug report.
The button would present a popup with copyable text with version or settings you feel most important to include in issues.  You could even could pre-populate the github issue form with a request to include that config info, along with instructions for how to retrieve it.

[ Also could we get a version number include in cauldron-notebook?  `cauldron.__version__` isn't defined, and there doesn't seem to be any other internal storage of version info.

```
# jinja has version info
$ python -c 'import jinja2; print(jinja2.__version__)'
2.8

# cauldron does not :-(
$ python -c 'import cauldron; print(cauldron.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'cauldron' has no attribute '__version__'
```

]

The config info available from the UI might include,

```
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1004

Versions:
python: Python 3.5.2
cauldron UI: 1.270.509
beautifulsoup4 (4.5.1)
cauldron-notebook (0.0.16)
certifi (2016.8.31)
click (6.6)
Flask (0.11.1)
itsdangerous (0.24)
Jinja2 (2.8)
Markdown (2.6.6)
MarkupSafe (0.23)
numpy (1.11.1)
pandas (0.18.1)
pip (8.1.2)
Pygments (2.1.3)
python-dateutil (2.3)
pytz (2016.6.1)
setuptools (26.1.1.post20160901)
six (1.10.0)
Werkzeug (0.11.10)
wheel (0.29.0)
```

**Comment by sernst** [comment]
Good feedback @cswarth. I've add cauldron.__version__ to the v0.0.17 release, and I will work on integrating collected version information into the next release.
