### ISSUE TITLE
unexpected behavior when setting filename for step

### ISSUE THREAD

**Issue by cswarth** [sernst/cauldron#4]
I noticed some unexpected behavior when setting the name of a step.
![step-name](https://cloud.githubusercontent.com/assets/295428/18795551/f44d2416-8179-11e6-828b-7e71c493e7d6.png)

There is an asterisk above filename that I don't understand.  Is that providing some sort of warning?

If one includes a filename extension in the name of the step, the UI appears to incompletely remove the extension before creating the filename.  I also have to ask why not let me call the filename anything I want, instead of prepending "S0-" onto the front?  Is the S0 used to order the steps in the notebook?

![step-name2](https://cloud.githubusercontent.com/assets/295428/18795739/d576b42a-817a-11e6-9d67-6990e0148040.png)

**Comment by cswarth** [comment]
I also noticed that the filenames  associated with the step are inconsistent, showing both "S03-myprogram..py" and "s03.py".

![step3](https://cloud.githubusercontent.com/assets/295428/18796213/16e94344-817d-11e6-96b1-3103f9d4a66c.png)

**Comment by sernst** [comment]
Regarding the asterisk. Following Google's latest Material Design UI/UX specifications, an asterisk should be next to required text fields. See the documentation for [Material Design Text Input Fields](https://material.google.com/components/text-fields.html#text-fields-search-filter) for more details if interested.
 
However, this field was erroneously marked required when it is not and that attribute has been removed in the latest UI release.

**Comment by sernst** [comment]
> If one includes a filename extension in the name of the step, the UI appears to incompletely remove the extension before creating the filename.

Thanks for pointing this out. It has been fixed in the latest UI release.

**Comment by sernst** [comment]
> I also have to ask why not let me call the filename anything I want, instead of prepending "S0-" onto the front? Is the S0 used to order the steps in the notebook?

@cswarth That is correct, the "S##-"  filename prefix is applied by default to order the steps when viewed in finder or explorer so that match the order of the notebook. This auto-prefixing can be disabled by checkbox when creating a notebook. I will work on improving the clarity of that checkbox's purpose. It is also planned that you will be able to turn the prefixing on and off inside a notebook settings view, which is on the feature roadmap.
