### ISSUE TITLE
cannot delete steps whose name includes spaces

### ISSUE THREAD

**Issue by cswarth** [sernst/cauldron#5]
1. Name a step to include a space in the name.
2. Delete that step.  Whether you check the box to remove the file doesn't matter.
3. (not) Profit!

Attempting to remove a step with a space in the name will result in an endlessly spinning arrow icon.

![screen shot 2016-09-23 at 11 16 38 am](https://cloud.githubusercontent.com/assets/295428/18796815/c95d5540-817f-11e6-9ea0-7270b51d9301.png)

![screen shot 2016-09-23 at 11 16 47 am](https://cloud.githubusercontent.com/assets/295428/18796817/c960cf04-817f-11e6-8313-e770b6473889.png)

![screen shot 2016-09-23 at 11 16 57 am](https://cloud.githubusercontent.com/assets/295428/18796816/c95f479c-817f-11e6-8fdd-29d3f3f9e973.png)

**Comment by sernst** [comment]
Nice catch. It has been fixed in the latest UI release.
