### ISSUE TITLE
Error trying to produce simple bar graph with Matplotlib

### ISSUE THREAD

**Issue by DanMayhew** [sernst/cauldron#7]
I get the error, "signal only works in main thread" in Cauldron when I run the code in the image.  I can run the code in Pycharm and produce the graph.

![bar graph error in cauldron](https://cloud.githubusercontent.com/assets/5333945/19776152/d579f456-9c27-11e6-9667-3ebb1493f2d9.PNG)
![bar graph in pycharm](https://cloud.githubusercontent.com/assets/5333945/19776151/d5781528-9c27-11e6-8897-599b9a167967.PNG)

**Comment by sernst** [comment]
The issue resides in the use of `plt.show()`. In Cauldron, everything is added to the notebook display by calling functions in the `cd.display` module. This is true of Matplotlib plots as well. To get the outcome you were expecting, replace `plt.show()` with `cd.display.pyplot()`.
