### ISSUE TITLE
macOS app Python selector doesn't allow continuing after using file picker

### ISSUE THREAD

**Issue by kcarnold** [sernst/cauldron#8]
The button only gets enabled after typing on the line. Or maybe I'd selected something wrong first and fixed it, but it didn't realize that until I typed on the line.

Also, it's not clear whether you should pick the "python.app" or not.

Well, best thing would be to be able to pick from a list that defaults to the interpreter you actually use, like jupyter notebook does. Maybe just use its list?

**Comment by sernst** [comment]
This has been resolved in the latest release.
